version: "3"

services:
  front:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    command: sh -c "rm -rf /app/.nuxt /app/.output /app/.nitro /tmp/nitro && yarn dev"
